### ISSUE TITLE
Double Scroll bar Admin Page

### ISSUE THREAD

**Issue by SafeDuck** [bearhack-ucr/bearhack2024#94]
![image](https://github.com/bearhack-ucr/bearhack2024/assets/49844738/b89cb505-e982-4054-a596-1415d0adc129)

**Comment by NovaSagittarii** [comment]
issue narrowed down to inner page's overflow behavior (the outer scrollbar appears as a result of the left sidebar)

**Comment by stanleylew5** [comment]
![image](https://github.com/bearhack-ucr/bearhack2024/assets/135681592/b4437fcb-9a34-4314-9490-abaf1d167f06)
guys i dont see it

**Comment by NovaSagittarii** [comment]
happens when you start zooming in (aka smaller screens)

![image](https://github.com/bearhack-ucr/bearhack2024/assets/12877445/78ca5b9a-c83e-42f6-99e6-df57eea06925)

the outer scrollbar occurs when the left sidebar overflows
the inner scrollbar happens when the right content part overflows

**Comment by NovaSagittarii** [comment]
https://github.com/acm-ucr/hackathon-website/issues/1252

**Comment by NovaSagittarii** [comment]
fixed with
https://github.com/acm-ucr/hackathon-website/pull/1274
