### ISSUE TITLE
Animate tracks

### ISSUE THREAD

**Issue by SafeDuck** [bearhack-ucr/bearhack2024#95]
give each a bouncing a effect
![image](https://github.com/bearhack-ucr/bearhack2024/assets/49844738/697d20f9-0418-4c7a-a1a3-30cf4ed41b17)

**Comment by NovaSagittarii** [comment]
Relevant files:
- https://github.com/bearhack-ucr/bearhack2024/blob/dev/src/components/static/Tracks.jsx
- https://github.com/bearhack-ucr/bearhack2024/blob/dev/tailwind.config.js (if you use a custom animation)
